import analysis from "../../public/analysis.json";
import type { Analysis, SkuChannelRow } from "./types";

/**
 * The payload is generated by `python src/build_analysis.py`, which routes every
 * calculation through src/metrics.py — the module protected by checkpoint.json.
 * This file only reads, never recomputes.
 */
export const data = analysis as unknown as Analysis;

export function rowsForSku(sku: string): SkuChannelRow[] {
  return data.all_rows.filter((row) => row.sku === sku);
}

export function findSku(sku: string): SkuChannelRow | undefined {
  return data.all_rows.find((row) => row.sku === sku);
}

export function skuList(): { sku: string; name: string; category: string }[] {
  const seen = new Map<string, { sku: string; name: string; category: string }>();
  for (const row of data.all_rows) {
    if (!seen.has(row.sku)) {
      seen.set(row.sku, { sku: row.sku, name: row.name, category: row.category });
    }
  }
  return [...seen.values()];
}

export function byCategory(): { category: string; rows: SkuChannelRow[] }[] {
  const grouped = new Map<string, SkuChannelRow[]>();
  for (const row of data.all_rows) {
    const list = grouped.get(row.category) ?? [];
    list.push(row);
    grouped.set(row.category, list);
  }
  return [...grouped.entries()]
    .map(([category, rows]) => ({ category, rows }))
    .sort((a, b) => a.category.localeCompare(b.category));
}